### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by RYucel** [regstuff/whisper.cpp_windows#1]
I just recently found your repo and would like to try it on a windows 10 machine. How can I setup and run the whisper windows executable to get a transcription of a sound file?

**Comment by regstuff** [comment]
Download the zip from the Releases page. 
Unzip it. 
Download a model from https://ggml.ggerganov.com/  (let's say ggml-model-whisper-small.bin) and save it into the same folder.
Go into the unzip folder, and launch a command line in it. (Type cmd in the address bar of the explorer window once you're in the folder)
Make sure your audio file is a wav file with 16000 Hz sample rate. Use ffmpeg to convert: ffmpeg -i file.mp3 -ar 16000 -ac 1 -b:a 96K -acodec pcm_s16le file.wav
Then paste this into the command line (replace file.wav with the actual filename):
`main -m ggml-model-whisper-small.bin -t 4 -otxt -f file.wav`

**Comment by RYucel** [comment]
> main -m ggml-model-whisper-small.bin -t 4 -otxt -f file.wav

Worked like a charm! Thank you very much. A few more questions if possible for you: How can I set language for transcribe and job type as transcription not translation as a command line command?
